PHUNBASE:addRegularSound("WW2.Movement1", {"universal/movement1.wav", "universal/movement2.wav", "universal/movement3.wav", "universal/movement4.wav", "universal/movement5.wav", "universal/movement6.wav", "universal/movement7.wav", "universal/movement8.wav", "universal/movement9.wav", "universal/movement10.wav", "universal/movement11.wav", "universal/movement12.wav"})
PHUNBASE:addRegularSound("WW2.Movement2", {"universal/movement13.wav", "universal/movement14.wav", "universal/movement15.wav", "universal/movement16.wav", "universal/movement17.wav", "universal/movement18.wav", "universal/movement19.wav", "universal/movement20.wav", "universal/movement21.wav"})
PHUNBASE:addRegularSound("WW2.DrawSMG", {"universal/smg_draw_1.wav", "universal/smg_draw_2.wav", "universal/smg_draw_3.wav"})
PHUNBASE:addRegularSound("WW2.HolsterSMG", {"universal/smg_holster_1.wav", "universal/smg_holster_2.wav", "universal/smg_holster_3.wav"})
PHUNBASE:addRegularSound("WW2.DrawRifle", {"universal/rifle_draw_1.wav", "universal/rifle_draw_2.wav", "universal/rifle_draw_3.wav"})
PHUNBASE:addRegularSound("WW2.HolsterRifle", {"universal/rifle_holster_1.wav", "universal/rifle_holster_2.wav", "universal/rifle_holster_3.wav"})
PHUNBASE:addRegularSound("WW2.DrawPistol", {"universal/Pistol_draw_1.wav", "universal/Pistol_draw_2.wav", "universal/Pistol_draw_3.wav"})
PHUNBASE:addRegularSound("WW2.HolsterPistol", {"universal/Pistol_holster_1.wav", "universal/Pistol_holster_2.wav", "universal/Pistol_holster_3.wav"})
PHUNBASE:addRegularSound("WW2.DrawLauncher", {"universal/launcher_draw_1.wav", "universal/launcher_draw_2.wav", "universal/launcher_draw_3.wav"})
PHUNBASE:addRegularSound("WW2.HolsterLauncher", {"universal/launcher_holster_1.wav", "universal/launcher_holster_2.wav"})
PHUNBASE:addRegularSound("WW2.Breathe", "universal/idle_breathing.wav")
