PHUNBASE:addRegularSound("mosin.boltlatch", "weapons/mosin/boltlatch.wav")
PHUNBASE:addRegularSound("mosin.boltback", "weapons/mosin/boltback.wav")
PHUNBASE:addRegularSound("mosin.boltrelease", "weapons/mosin/boltrelease.wav")
PHUNBASE:addRegularSound("mosin.boltforward", "weapons/mosin/boltforward.wav")
PHUNBASE:addRegularSound("mosin.clipin", "weapons/mosin/clipin.wav")
PHUNBASE:addRegularSound("mosin.roundsin", "weapons/mosin/roundsin.wav")
PHUNBASE:addRegularSound("mosin.fire", "weapons/mosin/fire.wav")
PHUNBASE:addRegularSound("mosin.clipout", "weapons/mosin/clipout.wav")
PHUNBASE:addRegularSound("mosin.bulletin", "weapons/mosin/bulletin1.wav", "weapons/mosin/bulletin2.wav", "weapons/mosin/bulletin3.wav", "weapons/mosin/bulletin4.wav")
PHUNBASE:addRegularSound("mosin.drawfirst", "weapons/mosin/draw_first.wav")